### ISSUE TITLE
What is the state of this project?

### ISSUE THREAD

**Issue by piotrkubisa** [ZDmitry/react-native-redis#1]
I have notice this repository has not updated for 6 months and also code for the iOS is only in the dev branch, so I have concerns that project has stopped been maintained. 

@ZDmitry I would be grateful if you tell me how is the state of this project? What is missing? Have you found out any other implementations for RN-redis which satisfies your needs? Why iOS implementation haven't yet matured to `master` branch? Also, have you used it in production environment?

**Comment by ZDmitry** [comment]
Yes, right now maintaince is suspended. But still, I'm planing to add iOS support for it in the future. Right now there is only android part which is used in our other project in production. Actually that project required Redis support but I couldn't find any usable RN modules for this, so that made it by myself. Meanwhile I have no time to support it, but I'm planning to finish iOS part when I will have some time for it. Definitely not for now and I can't say precisely when I will come back to finish it.

So at this condition, please feel free to fork plugin, so that you can fine tune it for your needs.

**Comment by piotrkubisa** [comment]
Thank you very much for the quick and precise response.
